name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: '1.0.3'
      - name: Install dependencies
        run: wally install
      - name: Build
        run: rojo build plugin.project.json --output plugin.rbxm
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: plugin
          path: plugin.rbxm
